general.import = [
	'./catppuccin-mocha.toml'
]

[env]
TERM = "xterm-256color"

[window]
decorations = "None"
opacity = 0.8

[font]
size = 12.0

[font.normal]
family = "Go Mono Nerd Font Mono"
# family = "JetBrains Mono Nerd Font"
style = "Regular"


[selection]
save_to_clipboard = true
